-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tours
(
    tour_id integer,
    name character varying(50),
    description character varying(5000),
    duration smallint,
    price numeric(10),
    max_people smallint,
    PRIMARY KEY (tour_id)
);

CREATE TABLE IF NOT EXISTS public.guides
(
    guide_id integer,
    last_name character varying(70),
    first_name character varying(70),
    middle_name character varying(70),
    phone character varying(50),
    email character varying(100),
    rating numeric(3, 2),
    language character varying(3),
    accreditation_valid boolean,
    PRIMARY KEY (guide_id)
);

CREATE TABLE IF NOT EXISTS public.tour_instance
(
    instance_id integer,
    tour_id integer REFERENCES tours(tour_id),
    guide_id integer REFERENCES guides(guide_id),
    start_date date,
    end_date date,
    guide_vacancy boolean,
    status_active boolean,
    PRIMARY KEY (instance_id)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id integer,
    last_name character varying(70),
    first_name character varying(70),
    middle_name character varying(70),
    passport_identification character varying(12),
    phone character varying(20),
    email character varying(100),
    birthdate date
	PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    booking_id integer,
    customer_id integer REFERENCES customers(customer_id),
    instance_id integer,
    booking_date date,
    total_price smallint,
    status_active boolean,
    PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id integer,
    booking_id integer REFERENCES bookings(booking_id),
    amount smallint,
    payment_date date,
    method character varying(50),
    status_active boolean,
    PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.excursions
(
    excursion_id integer,
    name character varying(50),
    description text,
    location character varying(100),
    duration_days smallint,
    PRIMARY KEY (excursion_id)
);

CREATE TABLE IF NOT EXISTS public.tour_excursions
(
    tour_excursion_id integer,
    instance_id integer REFERENCES tour_instance(instance_id),
    excursion_id integer REFERENCES excursions(excursion_id),
    date date,
    PRIMARY KEY (tour_excursion_id)
);

CREATE TABLE IF NOT EXISTS public.address
(
    address_id integer,
    address_1_string character varying(170),
    region character varying(50),
    city character varying(50),
    street character varying(50),
    building character varying(20),
    PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS public.hotels
(
    hotel_id integer,
    address_id integer REFERENCES address(address_id),
    name character varying(50),
    rating numeric(3, 2),
    PRIMARY KEY (hotel_id)
);

CREATE TABLE IF NOT EXISTS public.tour_hotels
(
    tour_hotel_id integer,
    instance_id integer REFERENCES tour_instance(instance_id),
    hotel_id integer REFERENCES hotels(hotel_id),
    date_checkin date,
    date_checkout date,
    PRIMARY KEY (tour_hotel_id)
);

END;